[features]
seeds = false
skip-lint = false

[programs.devnet]
todo = "3w3a64MegUHZuRRWP7xFyTzxxviKW7SM8WF7AmvYHW8h"


[programs.localnet]
todo = "BQkweE52J7zTjNNc45LAMsJtSFh23VwUmABiui9jVYpn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/disonek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
devnet = "solana config set --url devnet"
localnet = "solana config set --url localhost"