[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_bootcamp_group6 = "4QAYAnQDAYqmV2Nqq2WKmMaCipmZYp1T3xibZoJ9vm8F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/disonek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
